nginx:
  image: nginx
  restart: always
  ports:
     - "3000:80"
  links:
     - website
  volumes_from:
     - website

website:
  labels:
    - "Sitio web"
  image: busybox
  volumes:
    - ./public/:/usr/share/nginx/html
  command: tail -f /dev/null